### ISSUE TITLE
how to run this repo

### ISSUE THREAD

**Issue by Guaderxx** [playfulFence/esp-gallery#1]
My rust version is: rustc 1.79.0-nightly (8b2459c1f 2024-04-09).

When I compile with `cargo build --target riscv32imac-unknown-none-elf --release` :

```
error: no matching package named `esp32c3-hal` found
location searched: https://github.com/esp-rs/esp-hal.git
```

Then I found esp32cs-hal is deprecated, so I update the esp-hal :

```
error: failed to select a version for `esp-backtrace`.
    ... required by package `esp-gallery v0.1.0 (/*/esp-gallery)`
versions that meet the requirements `*` are: 0.11.1

the package `esp-gallery` depends on `esp-backtrace`, with features: `print-uart` but `esp-backtrace` does not have these features.


failed to select a version for `esp-backtrace` which could resolve this conflict
```

Seems the `esp-backtrace` also updated, so I update it again, change the feature `print-uart` to `println` : 

```
error: failed to select a version for `embedded-hal`.
    ... required by package `esp32s3-hal v0.7.0`
    ... which satisfies dependency `esp32s3-hal = "^0.7.0"` of package `esp-gallery v0.1.0 (/*/esp-gallery)`
versions that meet the requirements `=1.0.0-alpha.9` are: 1.0.0-alpha.9

all possible versions conflict with previously selected packages.

  previously selected package `embedded-hal v1.0.0`
    ... which satisfies dependency `embedded-hal = "^1.0.0"` of package `esp-hal v0.16.1 (https://github.com/esp-rs/esp-hal.git#a22b817e)`
    ... which satisfies git dependency `esp-hal` of package `esp-gallery v0.1.0 (/*/esp-gallery)`

failed to select a version for `embedded-hal` which could resolve this conflict
```

And now I'm confused, do you have time to fix this

**Comment by playfulFence** [comment]
Hello, @Guaderxx !
Sorry for not updating this example for a loooong-long time. I see that Real HW versions of examples still have some attention on them and yes, I think next week I'll allocate some time to fix this, thanks for the opened issue though!

PS: Also, please take a look into `Wokwi` version of this example! They are maintained and I'm trying to keep them up-to-date as much as possible: https://wokwi.com/projects/348033994448699987

**Comment by Guaderxx** [comment]
Glad to know you will fix this.
I'll take a look at your project. 
Actually, I found `Wokwi` is very interesting, so that I want run these examples in my computer.
